#!/usr/bin/env bash
set -euo pipefail

OPENCLAW_HOME="${OPENCLAW_HOME:-$(pwd)}"

if [[ -f "${OPENCLAW_HOME}/.env" ]]; then
  set -a
  # shellcheck disable=SC1090
  source "${OPENCLAW_HOME}/.env"
  set +a
fi

OPENCLAW_STATE_DIR="${OPENCLAW_STATE_DIR:-${OPENCLAW_HOME}/.openclaw}"
OPENCLAW_CONFIG_PATH="${OPENCLAW_CONFIG_PATH:-${OPENCLAW_STATE_DIR}/openclaw.json}"
OPENCLAW_WORKSPACE="${OPENCLAW_WORKSPACE:-${OPENCLAW_HOME}/workspace}"
OPENCLAW_GATEWAY_PORT="${OPENCLAW_GATEWAY_PORT:-40382}"

mkdir -p "${OPENCLAW_STATE_DIR}"
mkdir -p "${OPENCLAW_WORKSPACE}"

echo "Starting OpenClaw gateway"
echo "OPENCLAW_HOME=${OPENCLAW_HOME}"
echo "OPENCLAW_STATE_DIR=${OPENCLAW_STATE_DIR}"
echo "OPENCLAW_CONFIG_PATH=${OPENCLAW_CONFIG_PATH}"
echo "OPENCLAW_WORKSPACE=${OPENCLAW_WORKSPACE}"
echo "PORT=${OPENCLAW_GATEWAY_PORT}"

exec env \
  OPENCLAW_HOME="${OPENCLAW_HOME}" \
  OPENCLAW_STATE_DIR="${OPENCLAW_STATE_DIR}" \
  OPENCLAW_CONFIG_PATH="${OPENCLAW_CONFIG_PATH}" \
  OPENCLAW_WORKSPACE="${OPENCLAW_WORKSPACE}" \
  openclaw gateway --port "${OPENCLAW_GATEWAY_PORT}"
